import { Box } from "@mui/material";
import Head from "next/head";
import DashboardPage from "../component/dashboard/DashboardPage";
import MainLayouts from "../layouts/MainLayouts";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by Next " />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayouts>
        <DashboardPage />
      </MainLayouts>
    </Box>
  );
}
